// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKuo14-Rc17aowiMRq9XdUtOR7iDcMgf8',
    appId: '1:553429085126:web:8cccc85b729c2bf1d6a0c7',
    messagingSenderId: '553429085126',
    projectId: 'busspass-58583',
    authDomain: 'busspass-58583.firebaseapp.com',
    databaseURL: 'https://busspass-58583-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'busspass-58583.firebasestorage.app',
    measurementId: 'G-KF3YBLFWBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrgAdEAGVM1mxIX2WXTjJyWhsHPMb-YaA',
    appId: '1:553429085126:android:9f12915d920c4923d6a0c7',
    messagingSenderId: '553429085126',
    projectId: 'busspass-58583',
    databaseURL: 'https://busspass-58583-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'busspass-58583.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs18bA1JvxXaMC5yUBjTU5yBZ3HdD4ZWY',
    appId: '1:553429085126:ios:5f54e6987a9fb852d6a0c7',
    messagingSenderId: '553429085126',
    projectId: 'busspass-58583',
    databaseURL: 'https://busspass-58583-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'busspass-58583.firebasestorage.app',
    iosBundleId: 'com.example.busspass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs18bA1JvxXaMC5yUBjTU5yBZ3HdD4ZWY',
    appId: '1:553429085126:ios:5f54e6987a9fb852d6a0c7',
    messagingSenderId: '553429085126',
    projectId: 'busspass-58583',
    databaseURL: 'https://busspass-58583-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'busspass-58583.firebasestorage.app',
    iosBundleId: 'com.example.busspass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKuo14-Rc17aowiMRq9XdUtOR7iDcMgf8',
    appId: '1:553429085126:web:6f439d1b4d0ea576d6a0c7',
    messagingSenderId: '553429085126',
    projectId: 'busspass-58583',
    authDomain: 'busspass-58583.firebaseapp.com',
    databaseURL: 'https://busspass-58583-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'busspass-58583.firebasestorage.app',
    measurementId: 'G-FG5L0JYVZL',
  );
}
